# APP INFO
smart.app:
  jwtSecret: "VFb0qJ1LRg_4ujbZoRMXnVkUgiuKq5KxWqNdbKq_G9Vvz-S1zZa9LPxtHWKa64zDl2ofkT8F6jBt_K4riU-fPg"
  jwtExpirationMs: 1200000
  jwtRefreshExpirationMs: 86400000

server:
  port: 8087
  servlet.context-path: "/"
  error.include-message: always

logging:
  level:
    org.springframework: info

spring:
  h2.console.enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  # MYSQL CONFIG
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/smart-4"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver